### ISSUE TITLE
 SW4STM32 not compiling 

### ISSUE THREAD

**Issue by spirit89** [alberto-grl/ARMRadio_SW#1]
Hello, using the article from hackaday.io I downloaded release 2.0 not release 1.17.0. The newest release 2.9 still is not working I have worked on this too long. Is there any change you could send release 1.17.0 or the bin file so I can test my board with great program.?

Thanks Dave

**Comment by alberto-grl** [comment]
Hello Dave,
Older versions of SW4STM32 can be found here:  https://www.ac6-tools.com/downloads/SW4STM32/
I'm not working on this project anymore, so basically you are on your own. All of my limited resources are now on an evolution of the same radio concept that uses an MCU of the STM32H7 family. Much higher working frequency, 4Mhz native or 8 or more with oversampling.
You can download the .elf file for the old STM32F4 here: https://github.com/alberto-grl/ARMRadio_SW/tree/master/ARMRadio_SW/Debug

Regards and thanks for the interest

Alberto I4NZX

**Comment by spirit89** [comment]
Hello Alberto,

Thanks for the links for files. All take a look at the TM32H7 family. and watch your new project.

Thanks again Dave
